### ISSUE TITLE
[Suggestion] use fake-useragent package

### ISSUE THREAD

**Issue by mnlbox** [pgaref/HTTP_Request_Randomizer#28]
Hi,
Thanks for your package. I suggest use https://pypi.python.org/pypi/fake-useragent for user_agent part. It seems good.
Here is get random user_agent steps with this package:
```python
from fake_useragent import UserAgent
ua = UserAgent()
print(ua.random)
```

**Comment by pgaref** [comment]
Hello @mnlbox 
It seems like a nice addition to the project - feel free to open a PR if you feel like contributing ;)
