### ISSUE TITLE
Parser Abstraction

### ISSUE THREAD

**Issue by pgaref** [pgaref/HTTP_Request_Randomizer#3]
Moving a step further, if we want to support numerous proxy providers it would be nice having a **Parser Abstraction** class and each specific parser to extend it

**Comment by ieguiguren** [comment]
Maybe this parser may manage error and notify parser's developer. At least, must avoid that errors in websites break the **Randomizer**

**Comment by pgaref** [comment]
First version of the abstraction is now implemented and released
