### ISSUE TITLE
BS4 error from samair proxy parser

### ISSUE THREAD

**Issue by Hessu1337** [pgaref/HTTP_Request_Randomizer#33]
`  File "/usr/lib/python3.6/site-packages/http_request_randomizer/requests/proxy/requestProxy.py", line 55, in __init__
    self.proxy_list += parsers[i].parse_proxyList()
  File "/usr/lib/python3.6/site-packages/http_request_randomizer/requests/parsers/SamairProxyParser.py", line 42, in parse_proxyList
    headings = [th.get_text() for th in table.find("tr").find_all("th")]
AttributeError: 'NoneType' object has no attribute 'find'`

**Comment by pgaref** [comment]
Hello @Hessu1337 

Samair proxy provider looks unreachable to me. For instance,  http://samair.ru/proxy/time-01.htm page returns a 404 error - that's why the specific proxy provider is skipped when I am listing all the available proxies. Are you sure the provider is reachable? 

Cheers,
Panagiotis

**Comment by Hessu1337** [comment]
Hi @pgaref ,

It's reachable for me, made a pull request with bs4 findAll fix and working like a charm here.

**Comment by pgaref** [comment]
Hello @Hessu1337 

I guess they introduced geo-restrictions. May I ask the location(country) of your parser?
Thanks for the PR, please check some inline comments in the PR.

Cheers,
Panagiotis

**Comment by Hessu1337** [comment]
Of course, the ip location is based in France.
