### ISSUE TITLE
requests module work slow

### ISSUE THREAD

**Issue by Spitzbergen** [pgaref/HTTP_Request_Randomizer#39]
I pip install http-request-randomizer then try to use it, but speed was too slow and i decide not to. But then my regular requests by reuqests module get extrimly slow, seems like it is still working through proxi. Then i pip uninstall http-request-randomizer, but it doesnt help, also i try to reinstall requests. 
Still requests working so slow. I'm a newbie in python please tell me what to do

**Comment by Spitzbergen** [comment]
Sorry, It was just unbelievable coincidence with low speed of my internet for specific urls

**Comment by pgaref** [comment]
@Spitzbergen I am glad you sorted things out! 
I consider this issue settled
