### ISSUE TITLE
Typo in installation instructions at pypi page

### ISSUE THREAD

**Issue by penguin2048** [pgaref/HTTP_Request_Randomizer#43]
The pypi page for the module at https://pypi.python.org/pypi/http-request-randomizer tells user to install the package using command `pip install http-requests-randomizer` instead of `pip install http-request-randomizer` i.e. 'requests' instead of 'request'

**Comment by pgaref** [comment]
@penguin2048 thanks for reporting!
I am updating pypi shortly
